import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
const inter = Inter({ subsets: ['latin'] })
export default function Home({userData}) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br />
      <h2>User List</h2>
      <ul>
         {userData.map((user) => (
          <li key={user.id} onClick={()=>router.push(`user/${user.id}`)} style={{
            color:'yellow', cursor:'pointer', margin:'10px'
          }}>
            {user.id}-{user.name}
          </li>
           )
         )}
      </ul>
     
    </>
  )
}
export const getStaticProps = async(context)=>{
  const res = await fetch('http://localhost:3000/api/users')
  const userData = await res.json()
  return{
    props:{
     userData,
    }
  }
}
